### ISSUE TITLE
Where is the "model.ckpt" ?

### ISSUE THREAD

**Issue by LOOKCC** [harubaru/waifu-diffusion#18]
Next you will want to download the starting checkpoint into the file model.ckpt
and where to download the "model.ckpt"? may be is  "wd-v1-2-full-ema.ckpt"?

**Comment by harubaru** [comment]
The model.ckpt is the full ema model. You can download it from a mirror here:

https://thisanimedoesnotexist.ai/downloads/wd-v1-2-full-ema.ckpt
