### ISSUE TITLE
prune.py broken since last commit

### ISSUE THREAD

**Issue by azumukupoe** [harubaru/waifu-diffusion#20]
you should revert https://github.com/harubaru/waifu-diffusion/commit/a4628125feacca98af1ecd8d9bdd50afcab4e122 as it seems to have broken the script

https://boards.4channel.org/g/thread/88891192#p88892496

![](https://i.4cdn.org/g/1664454177416229.jpg)

I've also noticed that `wd-v1-3-float16.ckpt` and `wd-v1-3-float32.ckpt` were apparently pruned using the updated script so you should check them as well

https://boards.4channel.org/g/thread/89078583/#p89079343

![](https://i.4cdn.org/g/1665265842772287.png)

**Comment by harubaru** [comment]
i've modified the pruning script used for the v1.3 models, i'll push the changes for it soon

**Comment by harubaru** [comment]
plus, float16 and the full float32 weights will give you different images anyway

**Comment by drdaxxy** [comment]
With v1.3 you get one of two results[^1], let's call them A and B, depending on weights file, `use_ema` parameter and whether you're in a `model.ema_scope()`:

| ckpt                 | use_ema   | ema_scope() | result |
|----------------------|-----------|-------------|--------|
| *#text-to-image bot* |           |             | A      |
| full                 | True      | yes         | B      |
| full                 | True      | no          | A      |
| **full**             | **False** | **yes**     | **A**  |
| full                 | False     | no          | A      |
| pruned               | True      | yes         | noise  |
| pruned               | True      | no          | B      |
| **pruned**           | **False** | **yes**     | **B**  |
| pruned               | False     | no          | B      |

The original CompVis codebase sets `use_ema: False` in `v1-inference.yaml` (and uses `ema_scope`) - and I think all popular forks kept this.

> [Float 32 Full Weights](https://huggingface.co/hakurei/waifu-diffusion-v1-3/blob/main/wd-v1-3-full.ckpt): The full weights contain the EMA weights which are not used during inference. These can be used for either training or inference.

That description is a little confusing:

- With `use_ema: False`, the code always looks for non-EMA weights to generate images.
- The *full* checkpoint contains *both EMA and non-EMA* weights, so images are generated with *non-EMA* weights (result A).
- The *pruned* checkpoints contain *only EMA* weights, but *renamed* to "non-EMA" so they're found despite `use_ema: False`, generating result B.

One could remove the EMA weights from the full checkpoint instead, producing files as small as Haru's pruned checkpoints that also generate result A.

> I would use the full wights if it gives different images

@azumukupoe The EMA weights *in theory* generate *better* results - I haven't seen an obvious winner when comparing the two, though - you just need both to continue training.

---

I was confused why (using pruned checkpoints) I couldn't replicate the bot's results so I took a look, hope this helps someone.

[^1]: *float16* is slightly less accurate than *float32* - but that's just a minor "glitchiness" difference, while A/B can be completely different pictures.

**Comment by harubaru** [comment]
Newer codebase does not have the pruning script, closing this issue
