### ISSUE TITLE
Which config yaml is suitable for FP16 training for GPU less than 30G ram?

### ISSUE THREAD

**Issue by eeyrw** [harubaru/waifu-diffusion#25]
I see a very new [configs/stable-diffusion/v1-4-finetune-test.yaml](https://github.com/harubaru/waifu-diffusion/blob/76efa00de305b4656e41354305cca73f84289aa6/configs/stable-diffusion/v1-4-finetune-test.yaml) which supports fp16. Is this one usable?

**Comment by harubaru** [comment]
You may need to adjust the batch size. I'm assuming you are going to be training with 24GB of VRAM?

**Comment by NilaierMusic** [comment]
I've seen your post on Twitter where you was training with 13-14 GB of VRAM. What was your setup, Haru?

**Comment by harubaru** [comment]
I used deepspeed with optimizer offloading, it doesn't really work right now because it needs special callbacks to save and load the model which is different from what PyTorch Lightning uses

**Comment by NilaierMusic** [comment]
> I used deepspeed with optimizer offloading, it doesn't really work right now because it needs special callbacks to save and load the model which is different from what PyTorch Lightning uses

Oh, so, no low vram finetuning? Sadge ;(

**Comment by laksjdjf** [comment]
I succeeded in fp16 finetuning with 14GB of VRAM by changing torch.optim.AdamW to bitsandbytes.optim.Adam8bit and use_ema:false

**Comment by NilaierMusic** [comment]
> I succeeded in fp16 finetuning with 14GB of VRAM by changing torch.optim.AdamW to bitsandbytes.optim.Adam8bit and use_ema:false

Where to change this stuff? Not in config and not in main.py, that's for sure

**Comment by laksjdjf** [comment]
ldm/models/diffusion/ddpm.py

**Comment by NilaierMusic** [comment]
> use_ema:false

ok, what about this line? Where do i need to replace this one?

**Comment by NilaierMusic** [comment]
> > use_ema:false
> 
> ok, what about this line? Where do i need to replace this one?

Oh, ok, i've found this one. But it still didn't work. Process was just killed after it tried to summon a checkpoint. Maybe it needs more than 12GB of RAM to load it in or a different model. I've used a pruned model, so maybe i need a full ema, but i doubt it. Probably just a RAM issue

**Comment by laksjdjf** [comment]
i think so. it didn't work by googlecolab standard runtime (RAM12.68GB)

**Comment by eeyrw** [comment]
> I succeeded in fp16 finetuning with 14GB of VRAM by changing torch.optim.AdamW to bitsandbytes.optim.Adam8bit and use_ema:false

It sounds quite helpful. What input image resolution do you use? 512x512? How about the finetune performance of FP16 and EMA free?

**Comment by laksjdjf** [comment]
> i think so. it didn't work by googlecolab standard runtime (RAM12.68GB)

i forgot to set batch size 1 :) it worked on batch size 1.

**Comment by laksjdjf** [comment]
> It sounds quite helpful. What input image resolution do you use? 512x512? How about the finetune performance of FP16 and EMA free?

i used 512×512.

↓ 2600 images 1 epoch.
https://assets.st-note.com/img/1665645837206-JFvejp0VpD.png

**Comment by NilaierMusic** [comment]
> > i think so. it didn't work by googlecolab standard runtime (RAM12.68GB)
> 
> i forgot to set batch size 1 :) it worked on batch size 1.

Even on Batch Size 1 doesn't work for me. Maybe i'm doing something wrong? All my images are 512x512. All of them are in img folder and all captions are in txt. I'm using a pruned model, so maybe i need to switch to full ema? I've specified my checkpoint and dataset in config and added all changes that we've already mentioned.

**Comment by eeyrw** [comment]
> > It sounds quite helpful. What input image resolution do you use? 512x512? How about the finetune performance of FP16 and EMA free?
> 
> i used 512×512.
> 
> ↓ 2600 images 1 epoch. https://assets.st-note.com/img/1665645837206-JFvejp0VpD.png

The quality of finetune is not quite ideal. Maybe iteration times are not enough.

**Comment by eeyrw** [comment]
@harubaru I tried the [configs/stable-diffusion/v1-4-finetune-test.yaml](https://github.com/harubaru/waifu-diffusion/blob/76efa00de305b4656e41354305cca73f84289aa6/configs/stable-diffusion/v1-4-finetune-test.yaml) with batch size =1. Turn out almost 24G RAM of GPU will be consumed. The GPU RAM will be overflow when logging images periodically. 
@laksjdjf Then I tried to set use_ema: False which reduce GPU RAM consuming significantly, but when logging images I got colorful noise images of reconstruction and sampling.

Conclusion:
If you train with GPU with 24G RAM with EMA you should turn off ImageLogger to do blind training.

**Comment by chavinlo** [comment]
Although this issue is a bit old, you should use the diffusers trainer instead. It's way more optimized than CompVis trainer and is able to run on 18GB of VRAM and 13GB of ram, in other words a 3090 and 16gigs of RAM should work flawlessly.
You can now also train on different aspect ratios and its more updated than the previous trainer.

**Comment by eeyrw** [comment]
I have noticed the update of new trainer based on huggingface diffusers in recent days. It's much clear than the original code and realize the variable aspect buckets more systematically. Great works!

**Comment by harubaru** [comment]
Hoping the newer trainer works for you, closing this issue unless something comes up with that.
